import { λIcon } from "@/ui/utils";

export type Glyph = 'Linux' | '';

export const GlyphMap: Array<λIcon | Glyph> = [
  'TriangleAlert',
  'CircleHelp',
  'CircleAlert',
  'ShieldAlert',
  'CircleCheck',
  'CircleX',
  'ShieldQuestion',
  'X',
  'Check',
  'Info',
  'Battery',
  'BatteryLow',
  'BatteryMedium',
  'BatteryFull',
  'BatteryCharging',
  'StickyNote',
  'Mail',
  'MailOpen',
  'Paperclip',
  'Flame',
  'HardDrive',
  'HardDriveDownload',
  'HardDriveUpload',
  'Key',
  'QrCode',
  'Barcode',
  'Ticket',
  'Usb',
  'ThumbsUp',
  'ThumbsDown',
  'Heart',
  'Biohazard',
  'Bitcoin',
  'Bluetooth',
  'BluetoothOff',
  'Bug',
  'Map',
  'MapPin',
  'MapPinOff',
  'MapPinned',
  'Fingerprint',
  'Sigma',
  'SquareSigma',
  'Radio',
]