name: release-tag
on:
  workflow_dispatch:
    inputs:
      major:
        description: "Major"
        required: true
      minor:
        description: "Minor"
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Create next fix tag
        id: rel
        run: |
          scripts/release.sh --major "${{ github.event.inputs.major }}" --minor "${{ github.event.inputs.minor }}"
      - name: Push tag
        run: git push --tags
